name: Daily Java+Angular Job Digest

on:
  schedule:
    # Runs at 06:30 UTC = 12:00 PM IST
    - cron: "30 6 * * *"
  workflow_dispatch: {}  # allow manual run

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job scraper and send email
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          EMAIL_SENDER_NAME: ${{ secrets.EMAIL_SENDER_NAME }}
        run: |
          python jobs_scraper.py
